name: R-check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ github_actions_test ]
  pull_request:
    branches: [ github_actions_test ]


jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        R: [ '3.6.1' ]
    name: R ${{ matrix.R }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup R
        uses: actions/setup-R@v1
        with:
          r-version: ${{ matrix.R }}
      - run: Rscript -e 'print("hello")'
