name: R-check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ github_actions_tests ]
  pull_request:
    branches: [ github_actions_tests ]


jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: '3.6.1'
      - run: Rscript -e 'print("hello"); print(version)'
        
